import { Certificate } from "@/lib/types";

export const mockCertificates: Certificate[] = [
  {
    id: "cert-soccerbot",
    title: "Sertifikat Soccerbot Competition",
    description: "Sertifikat partisipasi dalam kompetisi robotika Soccerbot, menunjukkan kemampuan dalam pemrograman robot dan kontrol sistem otomatis.",
    platform: "Robotics Competition",
    category: "Robotics",
    date: "2024",
    issuedBy: "Soccerbot Competition Organizer",
    credentialId: "SOCCERBOT-2024",
    verificationUrl: "#", // No online verification available for this competition
    skills: ["Robotics Programming", "Arduino", "Kotlin", "Hardware Control", "Competition Strategy"],
    pdfUrl: "/certificates/HASRINATA ARYA AFENDI _ Sertifikat Soccerbot.pdf",
  },
  {
    id: "cert-oracle-java",
    title: "Oracle Java Programming Certification",
    description: "Sertifikat resmi Oracle untuk pemrograman Java, mencakup fundamental programming, OOP, dan best practices dalam pengembangan aplikasi Java.",
    platform: "Oracle",
    category: "Programming",
    date: "2024",
    issuedBy: "Oracle Corporation",
    credentialId: "ORACLE-JAVA-2024",
    verificationUrl: "#", // No online verification URL available for this certificate
    skills: ["Java Programming", "Object-Oriented Programming", "Java SE", "Software Development"],
    pdfUrl: "/certificates/Sertifikat Oracle Java Programming.pdf",
  },
  {
     "id": "cert-android-expert",
  "title": "Prompt Engineering untuk Software Developer",
  "description": "Kursus ini membahas teknik lanjutan dalam merancang dan mengoptimalkan prompt untuk model bahasa besar (LLM) seperti ChatGPT dan Gemini. Fokus pada praktik terbaik dalam pengembangan software berbasis AI, integrasi LLM ke aplikasi, serta eksplorasi use-case dalam produktivitas, coding assistance, dan automasi.",
  "platform": "Dicoding",
  "category": "Artificial Intelligence",
  "date": "29 Mei 2025",
  "issuedBy": "Dicoding Indonesia",
  "credentialId": "753-4223383",
  "verificationUrl": "https://www.dicoding.com/certificates/753-4223383",
  "skills": [
    "Prompt Engineering",
    "LLM Integration",
    "AI-Assisted Development",
    "Software Automation",
    "Natural Language Processing"
  ],
  "pdfUrl": "/certificates/sertifikat_course_753_4223383_290525181429.pdf",
  },
  {
    id: "cert-backend-expert",
    title: "Menjadi Back-End Developer Expert",
    description: "Kursus expert-level backend development yang mencakup microservices, database optimization, security, dan scalable architecture.",
    platform: "Dicoding",
    category: "Backend Development",
    date: "26 Mei 2025",
    issuedBy: "Dicoding Indonesia",
    credentialId: "382-4223383",
    verificationUrl: "https://www.dicoding.com/certificates/382-4223383",
    skills: ["Node.js", "API Design", "Microservices", "Database Optimization", "Security"],
    pdfUrl: "/certificates/sertifikat_course_382_4223383_260525230416.pdf",
  },
  {
    id: "cert-devops",
    title: "Belajar DevOps untuk Pemula",
    description: "Fundamental DevOps practices termasuk CI/CD, containerization dengan Docker, infrastructure as code, dan monitoring aplikasi.",
    platform: "Dicoding",
    category: "DevOps",
    date: "26 Mei 2025",
    issuedBy: "Dicoding Indonesia",
    credentialId: "600-4223383",
    verificationUrl: "https://www.dicoding.com/certificates/600-4223383",
    skills: ["DevOps", "CI/CD", "Docker", "Infrastructure as Code", "Monitoring"],
    pdfUrl: "/certificates/sertifikat_course_600_4223383_260525205629.pdf",
  },
  {
    id: "cert-web-intermediate",
    title: "Belajar Membuat Front-End Web untuk Pemula",
    description: "Pengembangan front-end web modern menggunakan HTML5, CSS3, dan JavaScript ES6+ dengan fokus pada responsive design dan best practices.",
    platform: "Dicoding",
    category: "Frontend Development",
    date: "26 Mei 2025",
    issuedBy: "Dicoding Indonesia",
    credentialId: "337-4223383",
    verificationUrl: "https://www.dicoding.com/certificates/337-4223383",
    skills: ["HTML5", "CSS3", "JavaScript ES6+", "Responsive Design", "Web Standards"],
    pdfUrl: "/certificates/sertifikat_course_337_4223383_260525174014.pdf",
  },
  {
    id: "cert-react",
    title: "Belajar Membuat Aplikasi Web dengan React",
    description: "Pengembangan aplikasi web modern menggunakan React.js, termasuk hooks, state management, dan integration dengan REST API.",
    platform: "Dicoding",
    category: "Frontend Development",
    date: "25 Mei 2025",
    issuedBy: "Dicoding Indonesia",
    credentialId: "615-4223383",
    verificationUrl: "https://www.dicoding.com/certificates/615-4223383",
    skills: ["React.js", "JavaScript", "Hooks", "State Management", "REST API"],
    pdfUrl: "/certificates/sertifikat_course_615_4223383_250525184854.pdf",
  },
  {
    id: "cert-web-fundamental",
    title: "Belajar Dasar Pemrograman Web",
    description: "Fundamental web development mencakup HTML, CSS, dan JavaScript dasar untuk membangun website interaktif dan responsive.",
    platform: "Dicoding",
    category: "Web Development",
    date: "25 Mei 2025",
    issuedBy: "Dicoding Indonesia",
    credentialId: "86-4223383",
    verificationUrl: "https://www.dicoding.com/certificates/86-4223383",
    skills: ["HTML", "CSS", "JavaScript", "Web Fundamentals", "DOM Manipulation"],
    pdfUrl: "/certificates/sertifikat_course_86_4223383_250525121934.pdf",
  },
  {
    id: "cert-js-fundamental",
    title: "Belajar Dasar Pemrograman JavaScript",
    description: "Fundamental JavaScript programming termasuk ES6+ features, asynchronous programming, dan modern JavaScript development practices.",
    platform: "Dicoding",
    category: "Programming",
    date: "24 Mei 2025",
    issuedBy: "Dicoding Indonesia",
    credentialId: "177-4223383",
    verificationUrl: "https://www.dicoding.com/certificates/177-4223383",
    skills: ["JavaScript", "ES6+", "Asynchronous Programming", "Functional Programming"],
    pdfUrl: "/certificates/sertifikat_course_177_4223383_240525230431.pdf",
  },
  {
    id: "cert-nodejs",
    title: "Belajar Membuat Aplikasi Back-End untuk Pemula",
    description: "Pengembangan backend menggunakan Node.js dan Hapi.js framework, termasuk RESTful API, database integration, dan testing.",
    platform: "Dicoding",
    category: "Backend Development",
    date: "21 Mei 2025",
    issuedBy: "Dicoding Indonesia",
    credentialId: "261-4223383",
    verificationUrl: "https://www.dicoding.com/certificates/261-4223383",
    skills: ["Node.js", "Hapi.js", "RESTful API", "Database", "Backend Architecture"],
    pdfUrl: "/certificates/sertifikat_course_261_4223383_210525134029.pdf",
  },
  {
    id: "cert-git",
    title: "Belajar Dasar Git dengan GitHub",
    description: "Version control menggunakan Git dan GitHub, termasuk branching strategies, collaboration workflows, dan best practices untuk tim development.",
    platform: "Dicoding",
    category: "Version Control",
    date: "20 Mei 2025",
    issuedBy: "Dicoding Indonesia",
    credentialId: "862-4223383",
    verificationUrl: "https://www.dicoding.com/certificates/862-4223383",
    skills: ["Git", "GitHub", "Version Control", "Branching", "Collaboration"],
    pdfUrl: "/certificates/sertifikat_course_862_4223383_200525235832.pdf",
  },
  {
    id: "cert-cloud-practitioner",
    title: "Cloud Practitioner Essentials (Belajar Dasar AWS Cloud)",
    description: "Fundamental cloud computing dengan AWS, mencakup core services, security, pricing, dan best practices untuk cloud deployment.",
    platform: "Dicoding",
    category: "Cloud Computing",
    date: "16 Mei 2025",
    issuedBy: "Dicoding Indonesia",
    credentialId: "653-4223383",
    verificationUrl: "https://www.dicoding.com/certificates/653-4223383",
    skills: ["AWS Cloud", "Cloud Computing", "Cloud Security", "Cloud Architecture"],
    pdfUrl: "/certificates/sertifikat_course_653_4223383_160525134057.pdf",
  },
  {
    id: "cert-programming-logic",
    title: "Belajar Dasar Pemrograman untuk Menjadi Software Developer",
    description: "Fundamental programming concepts, algoritma, struktur data, dan problem-solving techniques untuk software development.",
    platform: "Dicoding",
    category: "Programming",
    date: "12 Mei 2025",
    issuedBy: "Dicoding Indonesia",
    credentialId: "256-4223383",
    verificationUrl: "https://www.dicoding.com/certificates/256-4223383",
    skills: ["Programming Logic", "Algorithms", "Data Structures", "Problem Solving"],
    pdfUrl: "/certificates/sertifikat_course_256_4223383_120525185135.pdf",
  },
  {
    id: "cert-software-engineer",
    title: "Memulai Dasar Pemrograman untuk Menjadi Software Developer",
    description: "Introduction to software development lifecycle, programming paradigms, dan career path sebagai software developer professional.",
    platform: "Dicoding",
    category: "Software Engineering",
    date: "6 Mei 2025",
    issuedBy: "Dicoding Indonesia",
    credentialId: "251-4223383",
    verificationUrl: "https://www.dicoding.com/certificates/251-4223383",
    skills: ["Software Development", "SDLC", "Programming Paradigms", "Professional Development"],
    pdfUrl: "/certificates/sertifikat_course_251_4223383_060525225224.pdf",
  },
];